# fly.toml app configuration file generated for togglnotes-api on 2025-06-21T21:32:26-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'togglnotes-api'
primary_region = 'dfw'
kill_signal = 'SIGINT'  # This is the signal your app receives, as seen in the logs.
kill_timeout = 20       # Increase the grace period to 10 seconds.

[env]
DB_PATH = "/data/time_tracking.sqlite"

[build]
dockerfile = 'Dockerfile'

[[mounts]]
source = 'data'
destination = '/data'

[http_service]
internal_port = 8080
auto_start_machines = true

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
